## Transforming Code into Idiomatic Python
  - Replace traditional index manupulation with python core looping idiomatic

In [1]:
#Looping over a range of numbers - Traditional Approach
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [2]:
#Idiomatic Programming
for i in range(6):
    print(i**2,end=" ")

0 1 4 9 16 25 

## Looping Over a Collection

In [3]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [4]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

## Looping Backwards

In [5]:
colors = ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [7]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

## Looping to sorted list

In [8]:
colors = ['red','green','yellow','purple']
for color in sorted(colors):
    print(color,end=" ")

green purple red yellow 

In [9]:
colors = ['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

##
 - if x<=y and y<=z:
 - if x<=y<=z
 - if x==True
 - if x:

## Pandas

In [10]:
import pandas as pd

In [11]:
dt = {'Id':[11,12,13,14,15],
      'first_name':['A','B','C','D','E'],
      'company':['aa','bb','cc','dd','ee'],
      'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)

In [12]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [13]:
import os

In [ ]:
os.chdir("D:\\MyData") #Saves to certain location

In [19]:
mydt.to_csv("WorkingFile.csv",index = False)

In [22]:
pwd

'/home/student'

## Reading the data from CSV file

In [21]:
mydata = pd.read_csv('Workingfile.csv')

In [23]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [27]:
mydata1 = pd.read_csv('Workingfile.csv',skiprows=1,names=["CustId","Name","Company","Address"])

In [28]:
print(mydata1)

   CustId Name Company Address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd


In [30]:
mydata1 = pd.read_csv('Workingfile.csv',skiprows=[1,2,3],names=["CustId","Name","Company","Address"])

In [31]:
print(mydata1)

  CustId        Name  Company  Address
0     Id  first_name  company  address
1     14           D       dd      Hyd
2     15           E       ee      Hyd


## Numpy - Working with Multi Dimensional array
 - Numpy arrays are bit like python list
 - Numpy is also one of data structure
 - Numpy Short name for "Numeric Python" or "Numerical Python"

In [32]:
import numpy as np #import the numpy package

In [33]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [34]:
array=np.array(li) #convert the list into array
print(array)

[1 2 3 4 5]


In [35]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [36]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [38]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
